// components/header.tsx
import React from 'react'
import Links from './links'

interface Props {
  h1: String,
  h2?: String
}

export default function Header(props: Props) {
  const { h1, h2 } = props

  return (
    <div className="mt-10 sm:mt-20 mb-4">
      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-baseline">
        <h1 className="text-5xl font-bold">{h1}</h1>
        <h2 className="font-medium">{h2}</h2>
      </div>

      <hr className="mt-2 mb-1" />

      <Links />
    </div>
  )
}

// src/components/Header.vue
<script>
import { defineComponent } from "vue"
import Links from './Links.vue'

export default defineComponent({
  name: 'Header',
  components: {
    Links
  }
})
</script>

<template>
  <div class="mt-10 sm:mt-20 mb-4">
    <div class="flex flex-col sm:flex-row sm:justify-between sm:items-baseline">
      <h1 class="text-5xl font-bold">Simón Oroño</h1>
      <h2 class="font-medium">Computer Scientist & Software Developer</h2>
    </div>
    <hr class="mt-2 mb-1">
    <Links />
  </div>

</template>
